Repository g12-4soat/techlanches-infra-k8s, pull requests merged in 2024-03, with the labels that each got.

#5 add sg rules config
  src/data.tf
  src/eks_cluster.tf
Labels: bug, enhancement

#6 Feature/readme
  README.md
Labels: documentation

#7 service api loadbalancer
  k8s/deployments/techlanches-api-deployment.yaml
Labels: bug, enhancement

#10 addon eks
  src/eks_cluster.tf
Labels: enhancement

#11 correção execução pipeline
  src/eks_cluster.tf
Labels: bug
